# CI de nivel 03 - Disparo após a conclusão de um pipeline

name: 'Execucao por Deploy'

# regras de disparo (gatilhos/triggers) - gatilho de exec a partir de outro pipe = workflow_run
on:
  workflow_run:
    workflows: ['Execucao Manual']
    types:
      - completed

# O workflow será acionado quando o workflow 'Execucao Manual' for concluído com sucesso.
# Este arquivo é um exemplo de um workflow do GitHub Actions que é acionado após a conclusão de outro workflow.
# trabalhos/tarefas dentro do pipeline (jobs) - cada trabalho é um conjunto de etapas a serem executadas
jobs:
  e2e-tests:
    # Definindo o ambiente de execução onde o job irá executar
    # Neste caso, estamos usando a imagem do Ubuntu mais recente disponível no GitHub Actions
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Definindo os passos a serem executados dentro do trabalho
    steps:
      # Passo 1: Verificar o código-fonte do repositório
      - name: Check out code
        uses: actions/checkout@v4

      # Passo 2: Instalacao node.js
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Passo 3: Instalacao Yarn
      - name: install Yarn
        run: npm install -g yarn

      # Passo 4: Instalacao Dependências
      - name: Install dependencies
        run: yarn

      # Passo 5: Instalacao Playwright
      - name: Install Playwright
        run: yarn playwright install

      # Passo 6: Executar os testes E2E
      - name: Run E2E tests
        run: yarn run e2e

      # Passo 7: Upload do relatório do Playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report
